### ISSUE TITLE
[Research] Investigate use of SFTP server. Can it be retired entirely in favor of storing those things in VCS.

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#101]
Original context: https://github.com/OHS-Hosting-Infrastructure/infrastructure/pull/77#issuecomment-869721777

As the hosting team, we would like to understand how the SFTP server is used so that we can assess whether it can be done with any cloud services.

AC:
* [ ] SFTP use documented, including who uses it and how

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
