### ISSUE TITLE
[Research] Clarify use of Varnish and Cloudfront

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#102]
Before we can assess whether we can consolidate or separate functionality between Varnish and Cloudfront differently, we need to understand how they are used currently.

AC:
* [ ] Functionality and purpose of Varnish and Cloudfront systems are documented
* [ ] Recommendations for next steps are documented in ADR

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
