### ISSUE TITLE
[Research] Assess end user traffic demand

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#103]
As a hosting team, we need to understand how much traffic is going through the system so that we can determine whether we need redundant systems running between different regions or if we just need one.

Background:
There is a proposal to use us-west-1 environment to deploy using infrastructure as code methods, switch traffic to that environment temporarily, do the same on us-east-1 environment, and switch traffic back. We need to  know whether the two environments should be used as Blue/Green environments moving forward or whether us-west-1 will always be backup.

AC:
* [ ] Amount of traffic by source/region is documented
* [ ] Decision for how to use different environments is documented in ADR

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
