### ISSUE TITLE
Monthly maintenance July 2021

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#105]
IPD updates
- fix crontab
- add libssh2 to the instance and enable (running on Staging as of 07/07)

```
sudo apt install php7.4-ssh2
sudo service apache2 restart
php7.4 -i | grep ssh
```

OS Patches to apply

AC:
* Maintenance happening on the 22nd

**Comment by ssatagopan** [comment]
Maintenance window scheduled for 7/22
