### ISSUE TITLE
[User Submitted] Memory usage CRITICAL on ii-dev.east.eclkc

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#106]
## Reported By
@ssatagopan 

## Application Context
Unknown

## Environment Context
Dev

## Describe the issue
Getting a Nagios alert almost every day about memory usage on ii-dev.east.eclkc. Need to investigate and fix if possible.

## Impact
* Unknown

### Reproducibility
* Frequently

### Steps to reproduce the behavior:
1. Not sure

## Expected Behavior
No more memory warnings from this server

## Screenshots
***** Nagios *****

Notification Type: PROBLEM

Service: Memory Usage
Host: ii-dev.east.eclkc
Address: 10.1.6.10
State: CRITICAL

Date/Time: Sat Jul 10 00:05:03 EDT 2021

Additional Info:

CRITICAL - 9.7% (97880 kB) free!

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
