### ISSUE TITLE
[User Submitted] CPU Load on mail.east.eclkc CRITICAL

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#107]
## Reported By
@ssatagopan 

## Application Context
N/A

## Environment Context
Prod

## Describe the issue
Getting a weekly Nagios alert about CPU load being Critical on mail.east.eclkc

## Impact
* Unknown

### Reproducibility
Weekly

### Steps to reproduce the behavior:
1. Unknown

## Expected Behavior
CPU load is managed within bounds

## Screenshots
***** Nagios *****

Notification Type: PROBLEM

Service: CPU Load
Host: mail.east.eclkc
Address: 10.2.0.10
State: CRITICAL

Date/Time: Mon Jul 12 08:05:13 EDT 2021

Additional Info:

CRITICAL - load average: 15.12, 9.97, 4.43

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
