### ISSUE TITLE
[User Submitted] mariadb.east.eclkc/Disk Check - /var/backups is CRITICAL

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#108]
## Reported By
@ssatagopan 

## Application Context
N/A

## Environment Context
Prod

## Describe the issue
Getting Nagios alert every Friday about disk space from mariadb.east.eclkc

## Impact
* Unknown
* Team continues ignoring alerts
* We run out of space during backup and therefore don't have full backups from which to restore

### Reproducibility
Weekly

### Steps to reproduce the behavior:
1. Unknown

## Expected Behavior

An alert doesn't get generated because **the disk doesn't regularly run out of space during scheduled backups**.
This ticket should include an investigation and proposal for how to address lack of disk space while we move databases off this single instance.

Immediately apparent options include:
* Evaluate that alert.
* Increasing disk space
* Turning off alerts (BAD)
* Turning off backups (BAD)
* Moving backups elsewhere?
* Something better that YOU will uncover!!!!!!

## Screenshots
***** Nagios *****

Notification Type: PROBLEM

Service: Disk Check - /var/backups
Host: mariadb.east.eclkc
Address: 10.0.1.77
State: CRITICAL

Date/Time: Fri Jul 9 23:33:27 EDT 2021

Additional Info:

DISK CRITICAL - free space: /var/backups 11311 MiB (5.52% inode=100%):

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
