### ISSUE TITLE
Document phase 1 of research plan

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#11]
See https://github.com/OHS-Hosting-Infrastructure/infrastructure/tree/main/docs/user-research

Clean up and Add to phase 1.

Goal is to talk to dev teams about their applications and begin to learn about their ux as a team with an application hosted by headstart hosting.

Understand: data they contain and transfer, network configuration, is the app stateful/stateless etc. What is the dev team's understanding of their systems?

AC:
- Have an updated document containing phase 1 of research plan with goals and how this affects roadmap for the next month or so.
- create tickets for planned interviews

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
