### ISSUE TITLE
[ECLKC] Update SSL Cert for ECLKC

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#110]
Need to update SSL certificate for ECLKC

Have put cert file in 1Password in Truss vault

https://start.1password.com/open/i?a=FF4CVCYQBBCCVPBP6FIK7JXOJU&v=3t2c5rzdlybxn43ltwvytvkyum&i=ymfhsvaf2vewrmas6ioolkvguy&h=truss.1password.com

Notes:
* Manual update
* Stored in AWS ACM
* Need to configure LB to use it
* Varnish and maybe Mail server
* Can verify by hitting endpoints and check cert expiration date is past July 17, 2021

AC:
* [x] SSL certificate for ECLKC updated before July 17
* [ ] Procedure is documented in GitHub

**Comment by eeeady** [comment]
Need the private key to be useful at all. Asked Sanjay to ask the team to provide.

Rebecca, Jerel and I walked through the different locations the cert could be located and Rebecca wrote 1st draft instructions for swapping.

**Comment by eeeady** [comment]
Swapped the certs and added to the documentation.

Can close once we merge the docs.
