### ISSUE TITLE
[Critical] Update NodeJS package on DrupalDemo servers

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#111]
Need to update NodeJS packages on the following servers:

To be updated outside maintenance window:
* DrupalDemo1
* DrupalDemo2
* DrupalDemo3

There's [another ticket](https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/178) to do the remaining servers (* Varnish1, * Varnish2, ,* Lifeboat, * Jenkins).

See [scan results](https://docs.google.com/spreadsheets/d/1uPflOrTUhFbiq6LawHTRGS_aUrKHZwb9VNO-suamjao/edit?usp=sharing) for more details.

We need to update to NodeJS 12 on each machine.
It's unclear whether Sam of HSICC has done for both dev and staging for these servers, so check the versions of NodeJS running on each of the servers listed above and if they're not updated, update them.

AC:

- [x] NodeJS update is done to version 12 on DrupalDemo1, 2, and 3.
- [x] After changes, security scan does not find same vulnerabilities on server

**Comment by ssatagopan** [comment]
Changing ticket to be per update type instead of server based on discussion with team

**Comment by ssatagopan** [comment]
@ssatagopan to split ticket and create new for what needs to be updated in maintenance window

**Comment by kilbergr** [comment]
@ssatagopan 
This is asking for upgrade to v12. The latest is 16, the current stable is 14 (see docs: https://nodejs.org/en/about/releases/). What do you advise? I would suggest 14.

**Comment by kilbergr** [comment]
Drupal 1, 2, 3 updated to v12.
<img width="1021" alt="Screen Shot 2021-08-12 at 4 24 31 PM" src="https://user-images.githubusercontent.com/7401870/129282332-b4b074f7-6934-4e08-8d3d-1d86c82d8eb4.png">

**Comment by ssatagopan** [comment]
Scan results don't show same vulnerability anymore for these servers
