### ISSUE TITLE
[Critical] Update Ubuntu version

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#112]
We would like to use an AMI to deploy latest main line version of Ubuntu (20.x) to the ZTT dev servers:
- ZTTApps-Dev
- ZTTNotifications-Dev
- ZTTNAT-Dev

Would need to provide access to Mobisoft developers to these machines so that they can assess what packages are needed for their applications.

AC:

- [ ] AMI for Ubuntu 20.x available
- [ ] Deployed to ZTTApps-Dev and ZTTNotifications-Dev and ZTTNAT-Dev
- [ ] After changes, security scan does not find same vulnerabilities on servers
- [ ] Mobisoft developers are provided SSH access with Engineer policy

**Comment by ssatagopan** [comment]
Assumption is Varnish 1 is done first so understanding can be leveraged for this ticket.

**Comment by ssatagopan** [comment]
Changing to be per update type instead of server based on discussions with team

**Comment by ssatagopan** [comment]
Discussed with Dela and we have longer to do POAM items now so we can proceed with doing an AMI with Ubuntu 20.x

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
