### ISSUE TITLE
[High] Update Apache httpd DEV

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#113]
Need to update Apache httpd on the following servers:
* ParadisoLMS-Dev

For more details, see latest [OS scan results](https://app.box.com/folder/143269631989?s=8l7r7h0s2isferfxacyhgra8u869kwsp).

More info at Apache - https://httpd.apache.org/security/vulnerabilities_24.html

AC:
- [x] Apache httpd is updated to 2.4.48
- [x] After changes, security scan does not find same vulnerabilities on server

**Comment by ssatagopan** [comment]
Changed ticket to be for type of change vs server after discussing with team

**Comment by kilbergr** [comment]
<img width="329" alt="Screen Shot 2021-08-17 at 3 06 03 PM" src="https://user-images.githubusercontent.com/7401870/129807009-03aa4305-287b-4cd7-a917-3ecf049e65f4.png">

**Comment by kilbergr** [comment]
At risk of seeming useless--I've rerun the OS scan and added to Box but I can't tell how to identify whether the vulnerability is still there. Searching for Apache I'm not sure which error I'm after. @ssatagopan do you have recommendations? Sorry!

**Comment by ssatagopan** [comment]
> At risk of seeming useless--I've rerun the OS scan and added to Box but I can't tell how to identify whether the vulnerability is still there. Searching for Apache I'm not sure which error I'm after. @ssatagopan do you have recommendations? Sorry!

There's a couple of ways to look at the results. First step is to look at the previous scan results to find out which vulnerabilities recommended upgrading Apache httpd. Then you can identify with the new scan or using the dashboard on Qualys whether the same vulnerabilities showed up after the new scan for the machine on which you upgraded, in this case ParadisoLMS-Dev.

So in the previous scan results, the vulnerability for this machine was "Apache HTTP Server Multiple Vulnerabilities"

In the Qualys dashboard, you can look at the Vulnerabilities page and find the vulnerability and make sure it's not found for the server you fixed:
![image](https://user-images.githubusercontent.com/13230145/129896146-5e13e824-58b3-45f5-b00e-001ac3decf21.png)
