### ISSUE TITLE
[Critical] Remediate Apache Struts vulnerability

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#115]
Need to update Apache Struts or remove if not being used from the following servers:
* Stage
* ECLKCDev

See [scan results](https://docs.google.com/spreadsheets/d/1uPflOrTUhFbiq6LawHTRGS_aUrKHZwb9VNO-suamjao/edit?usp=sharing) for more details.

Next steps: Eady to ask Sam whether Apache struts can be deleted all together.

Eady will update this ticket with the resulting info.

AC:

- [ ] Apache Struts package updated or removed
- [ ] After changes, security scan does not find same vulnerabilities on server

**Comment by ssatagopan** [comment]
Switching ticket to be per update type instead of server based on discussion with team

**Comment by eeeady** [comment]
Whoops. I did not mean to close this

**Comment by eeeady** [comment]
okay. Now I do. I deleted the offending war files.
