### ISSUE TITLE
[Moderate] Update Squid Package

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#116]
Need to update Squid package for the following servers to resolve vulnerabilities:
* Varnish1
* Varnish2
* DrupalDemo1
* DrupalDemo2
* DrupalDemo3
* Stage
* ECLKCDev
* Lifeboat

See [scan results](https://docs.google.com/spreadsheets/d/1uPflOrTUhFbiq6LawHTRGS_aUrKHZwb9VNO-suamjao/edit?usp=sharing) for more details.

AC:

- [ ] Squid package updated
- [ ] After changes, security scan does not find same vulnerabilities on server

**Comment by ssatagopan** [comment]
Changed ticket to be per update type instead of per server after discussion with team.

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
