### ISSUE TITLE
[Critical] Update PHP version on Coaching Companion server

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#117]
Need to patch/update Coaching Companion server to update PHP version.

Coaching Companion was found to have a version of PHP no longer supported, 7.0.x

Latest is 8.0.9

This will need to happen during a maintenance window. Goal is for September maintenance.

AC:

- [ ] PHP version updated
- [ ] After changes, security scan does not find same vulnerabilities on server

**Comment by ssatagopan** [comment]
@ssatagopan to send email to Dayton asking whether it's fine to upgrade PHP version

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
