### ISSUE TITLE
[Moderate] ADR for SSH cryptographic settings

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#128]
Need to assess SSH cryptographic settings and document what should be new settings to remediate scan results.

See latest scan results at:
https://acf-headstart.box.com/s/8l7r7h0s2isferfxacyhgra8u869kwsp

Likely asking Truss hive mind will yield appropriate advice, which you can record in the ADR.

AC:

- [ ] ADR for new SSH settings
- [ ] Ticket to implement new settings with appropriate communication

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
