### ISSUE TITLE
[POAM] System and Communication Protection Policy and Procedures

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#131]
As part of ATO review, we need to create and document System and Communication Protection Policy and Procedures to satisfy SA-09.

SA-09:
The organization:
a. Requires that providers of external information system services comply with organizational information security requirements and employ [appropriate security controls] in accordance with applicable federal laws, Executive Orders, directives, policies, regulations, standards, and guidance;
b. Defines and documents government oversight and user roles and responsibilities with regard  to external information system services; and
c. Employs [reviews of independent auditor reports (e.g., SAS 70, SSAE 16)] to monitor security control compliance by external service providers on an ongoing basis.

Additional FedRAMP Requirements and Guidance
Guidance: See the FedRAMP Documents page under Key Cloud Service Provider (CSP) Documents> Continuous Monitoring Strategy Guide
https://www.FedRAMP.gov/documents
Guidance: Independent Assessors should assess the risk associated with the use of external services. See the FedRAMP page under Key Cloud Service Provider (CSP) Documents>FedRAMP Authorization Boundary Guidance

See https://acf-headstart.box.com/s/dzrw2lcs1gzrtxli5ngteq5vmvtealr7 for more info

AC:
* [ ] Policy and Procedures document available
* [ ] Reviewed by Alana

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
