### ISSUE TITLE
ADR for our ideal monitoring and alerting approach

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#135]
We need to explain what we expect from our monitoring and alerting. This is part of a 2 phased approach: first to implement something we can use now, and then to describe the path we ultimately want to pursue.

This ADR is for the ideal case. It should include preferred tooling and rationale as well as an on-call rotation plan. 

Constraints:
* During business hours, on-call to respond to bugs.
* If site is completely down, have to be available to fix.

This is a description of a built-out system with multiple integrations. It may provide helpful guidance, but will likely be more built out than we will get to: https://github.com/trussworks/Engineering-Playbook/blob/main/infrasec/aws/sns-guardduty-alert-integrations.md

AC:

-[ ] ADR describing desired monitoring and alerting approach for OHS hosting team

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
