### ISSUE TITLE
ADR for current monitoring and alerting approach

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#136]
We need to explain what we expect from our monitoring and alerting. This is part of a 2 phased approach: first to implement something we can use now, and then to describe the path we ultimately want to pursue.

This ADR is for what we will implement to manage our current state. It should include tools we expect to use immediately.

Constraints:
* During business hours, on-call to respond to bugs.
* If site is completely down, have to be available to fix.

AC:

- [ ] ADR describing current monitoring and alerting approach for OHS hosting team

**Comment by ssatagopan** [comment]
See QASP for requirements for support: https://acf-headstart.box.com/s/tq9p7rr1a4ext8k1ai0ic22zxkpak1xo

**Comment by ssatagopan** [comment]
Here is content related to Incidents from our contract:

FISMA defines an incident as “an occurrence that (1) actually or imminently jeopardizes, without lawful authority, the integrity, confidentiality, or availability of information or an information system; or (2) constitutes a violation or imminent threat of violation of law, security policies, security procedures, or acceptable use policies. 

The Contractor (and/or any subcontractor) shall comply with OHS’s Incident Response Policy dated July 10, 2018, including any subsequent updates.

In the event of a suspected or confirmed incident or breach, the Contractor (and/or any subcontractor) shall: 
1) Protect all sensitive information, including any PII created, stored, or transmitted in the performance of this contract so as to avoid a secondary sensitive information incident. 
2) Notify affected individuals only as instructed by the Contracting Officer or designated representative. 
3) Report all suspected and confirmed information security and privacy incidents and breaches to the OHS Incident Response Team (IRT), COR, CO, OHS SOP (or his or her designee), and other stakeholders, including incidents involving PII, in any medium or form, including paper, oral, or electronic as defined in OHS’s Incident Response Policy. 
4) Provide full access and cooperate on all activities as determined by the Government to ensure an effective incident response, including providing all requested images, log files, and event information to facilitate rapid resolution of sensitive information incidents. This may involve disconnecting the system processing, storing, or transmitting the sensitive information from the Internet or other networks or applying additional security controls. This may also involve physical access to contractor facilities during a breach/incident investigation.

**Comment by ssatagopan** [comment]
Another source for our procedure is the Incident Response Plan from our ATO. See section 3.3: https://acf-headstart.box.com/s/qvvzav6qy6swy7i6dj5a6125uw8ws29q

**Comment by ssatagopan** [comment]
Have put workflow of actions into flowchart: https://drive.google.com/file/d/1Trx0TCZjoTdrObiZ2cE1RK7jguIC9y8f/view?usp=sharing

**Comment by kilbergr** [comment]
I really didn't get far--
https://github.com/OHS-Hosting-Infrastructure/infrastructure/pull/new/rek-136-monitoring-adr
