### ISSUE TITLE
Automate cert renewal process for all relevant servers

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#137]
Our SSL certs should be using ACM to automatically apply so we don't have to manually replace them on expiration.

Set up ACM so it is tracking and replacing certs.

Need to make sure the following servers' certs are accounted for:

* ECLKC LB
* Varnish1
* Varnish2
* Cloudfront
* ...

Generating CSRs will be done separately.

AC:

- [ ] SSL certs are automatically applied within ACM

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
