### ISSUE TITLE
Investigate OS scan results

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#139]
Results of OS scan run on July 15 seem to indicate that OS patches hadn't been applied to several machines. We need to understand whether this is true or if there's something wrong with the scan itself.

Blocks all OS scan remediation tickets

AC:

- [x] Reasons for OS scan results is understood and documented in this ticket
- [x] If any tickets are needed to fix OS scan, they are created

**Comment by eeeady** [comment]
HAHA! We had several kernels installed on the servers that was interfering with the scan results. Everything looks good on the latest scan!
