### ISSUE TITLE
[POAM] SOP for Account Management

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#140]
We need to develop a Standard Operating Procedure (SOP) for Account Management working with our stakeholder app teams, primarily HSICC, as part of our System Security Plan documentation.

See section 2.11.6 in [SSP](https://acf-headstart.box.com/s/vx32bq6mpns73cq2mbmrdkoj1qjhnfpq)

Due by end of October

AC:

- [ ] SOP for Account Management available
- [ ] Internally reviewed (hosting team and 18F)

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
