### ISSUE TITLE
[POAM] Usage Monitoring

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#142]
As part of our security controls, we need to implement usage monitoring to detect atypical usage patterns.

See AC-02(12) in controls spreadsheet: https://acf-headstart.box.com/s/dzrw2lcs1gzrtxli5ngteq5vmvtealr7

Probably epic

AC:

- [ ] Able to monitor usage of system for atypical behavior with alerts as necessary and possible responses documented

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
