### ISSUE TITLE
[POAM] Enforce password requirements according to security controls

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#144]
We need to enforce password requirements according to the control on IA-05(01) in the Controls spreadsheet.

https://acf-headstart.box.com/s/dzrw2lcs1gzrtxli5ngteq5vmvtealr7

Will need to talk to the app teams (mainly HSICC) to understand feasibility and implementation.

AC:

- [ ] System enforces password requirements as required

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
