### ISSUE TITLE
[POAM] Detailed Recovery Procedures for Appendix C in Contingency Plan

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#145]
We need to document detailed recovery procedures in Appendix C in the Contingency Plan.

https://acf-headstart.box.com/s/btmo2zc8vf6gwmty8js5ugoi71ehmezu

AC:

- [ ] Detailed Recovery Procedures documented in Appendix C in the Contingency Plan
- [ ] Internally reviewed and ready to submit

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
