### ISSUE TITLE
Get Jerel SSH access

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#146]
Jerel does not appear to have SSH access onto our servers. Rebecca doesn't know how to generate a key for them based on these instructions: https://github.com/OHS-Hosting-Infrastructure/infrastructure/pull/14/files#diff-cd71b94906c613830cc5a8b47b5344f20427dda2cf06cc87bd7069dc927fc5afR1

AC:

- [ ] Get Jerel access
- [ ] Document how to grant someone access

**Comment by ssatagopan** [comment]
Can close as Jerel has access and don't need to document current process
