### ISSUE TITLE
Check and remove unused plugins from Jenkins

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#15]
https://plugins.jenkins.io/plugin-usage-plugin/

The following have vulns in them

**Comment by eeeady** [comment]
![Screen Shot 2021-05-25 at 7 00 30 PM](https://user-images.githubusercontent.com/1760850/119591565-addd5700-bd8b-11eb-8148-6c300e255abb.png)

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
