### ISSUE TITLE
Credential Management

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#152]
As a hosting team member, I need to manage system credentials in secure and reusable way so that it's sustainable and resilient.

Background:
When trying to add a new email address for ECLKC, it was found that the credentials for the Mail server administration was kept in Keepass. 
And instructions for accessing was kept in another document. This method of managing credentials is not optimal nor secure. The team needs to consolidate system credentials in a secure well-understood and documented location.

Outcome:
* Infrastructure system credentials are managed in a secure and well-understood system

AC:

- [ ] Write an ADR describing our cred management approach
- [ ] Create ticket to implement storage of infrastructure administration credentials in a secure system

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
