### ISSUE TITLE
ADR for Vulnerability Scanning

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#157]
We need to decide on what to use for our vulnerability scans moving forward. Currently we use Qualys. However, it's expensive and may not do everything we need.

Constraints: TODO
Requirements: TODO

AC:

- [ ] ADR with proposed scanning solution documented

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
