### ISSUE TITLE
[NCECDTL] Access to ZTTApps-Dev and ZTTNotifications-Dev for Mobisoft developers

### ISSUE THREAD

**Issue by lsoaterna** [OHS-Hosting-Infrastructure/infrastructure#158]
## Requested By
Luisa F. Soaterna 
lsoaterna@zerotothree.org

## Application Name
ELOF2GO, ELOF2GO in Spanish, and ELOF@HOME

## Purpose
We need to make updates to our ELOF2GO, ELOF2GO in Spanish, and ELOF@HOME mobile apps, and need access to the development server, and the staging and production servers for these mobile apps. 

[ELOF2GO- Server requirements.xlsx](https://github.com/OHS-Hosting-Infrastructure/infrastructure/files/6909523/ELOF2GO-.Server.requirements.xlsx)

## Description of this Change
Detailed information about the change being requested.

We will need the following individuals to have access to the dev server: 
1. abhijit.chaudhari@mobisoftinfotech.com
2. rushikesh.keskar@mobisoftinfotech.com
3. bhushan.patil@mobisoftinfotech.com
4. pratik.kale@mobisoftinfotech.com

* _Is this change a configuration change or a software change?_Configuration add on
* _Does this change require data schema migrations?_Not sure
* _Does this change fix a security vulnerability?_ no
* _What is the expected outcome and behavior?_in

## User Impact
Who does this impact? (i.e. Developers, application administrators, application end users) It impacts the server team and developers

## Timeline
Is there a deadline or any other timing considerations for this change? Could we have access to the server by August 15th. 

## Acceptance Criteria

- [ ] All documented Mobisoft users have VPN and SSH access to ZTTApps-Dev and ZTTNotifications-Dev servers
- [ ] Added users to VPN access list

BLOCKED BY:
https://github.com/orgs/OHS-Hosting-Infrastructure/projects/1#card-64991158

**Comment by lsoaterna** [comment]
I cannot answer this at the moment. We and the developers did not have access to these servers. We have a conversation at 12, would you like to join to confirm?

Luisa

**Comment by ssatagopan** [comment]
Closing as this is being worked on as part of the Ubuntu machine image ticket - https://ocio-jira.acf.hhs.gov/browse/OHSH-184

https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/112

**Comment by lsoaterna** [comment]
Can I get access to Jira? @ssatagopan

**Comment by ssatagopan** [comment]
@lsoaterna I've submitted a ticket to the JIRA admin last week so hopefully you will get access soon.
