### ISSUE TITLE
[User Submitted] ECLKC site intermittent outage

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#159]
## Reported By
UpTime Monitor

## Application Context
ECLKC site and CAS login pages

## Environment Context
Prod

## Describe the issue
The ECLKC site and associated pages seem to be going down intermittently. The issues started around 11:43PM ET with the [Login issu](https://github.com/orgs/OHS-Hosting-Infrastructure/projects/1#card-65819713)e, but the rest of the site went down around 2:40AM ET.

Since then, the site has been up and down. See attached [uptimerobot-ECLKC-logs.csv](https://github.com/OHS-Hosting-Infrastructure/infrastructure/files/6912783/uptimerobot-ECLKC-logs.csv).

## Impact
* All users

### Reproducibility
Seems to happen fairly often, almost once an hour

### Steps to reproduce the behavior:
1. Unknown

## Expected Behavior
Site stays up

## Additional Context
Some other Nagios notifications seen around this time:

Reported every hour since this first one:
** PROBLEM Service Alert: paradiso.east.eclkc/Disk Check is CRITICAL **
***** Nagios *****

Notification Type: PROBLEM

Service: Disk Check
Host: paradiso.east.eclkc
Address: 10.0.0.168
State: CRITICAL

Date/Time: Sat Jul 31 22:12:49 EDT 2021

Additional Info:

DISK CRITICAL - free space: / 8743 MB (5% inode=94%):

**Comment by eeeady** [comment]
Paradiso shouldn't affect it... have been looking for about 20 minutes.... I have attempted:

- restarting varnish
- restarting nginx

reading nginx logs....  it looks like php died

**Comment by eeeady** [comment]
at the top I see
```
2021/08/01 03:43:02 [error] 1484#1484: *2686588 FastCGI sent in stderr: "PHP message: PDOException: SQLSTATE[HY000] [1040] Too many connections in /var/www/drupal-composer-project/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupal-composer-project/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=10.0...', 'drupaluser', '1plsNotAnotherB...', Array)
#1 /var/www/drupal-composer-project/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /var/www/drupal-composer-project/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /var/www/drupal-composer-project/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /var/www/drupal-composer-project/web/core/lib/Drupal/Component/DependencyInjection/C" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /how-apply HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "eclkc.ohs.acf.hhs.gov", referrer: "https://eclkc.ohs.acf.hhs.gov/how-apply"
2021/08/01 03:43:02 [error] 1484#1484: *2686588 FastCGI sent in stderr: "PHP message: PDOException: SQLSTATE[HY000] [1040] Too many connections in /var/www/drupal-composer-project/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupal-composer-project/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=10.0...', 'drupaluser', '1plsNotAnotherB...', Array)
#1 /var/www/drupal-composer-project/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /var/www/drupal-composer-project/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /var/www/drupal-composer-project/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /var/www/drupal-composer-project/web/core/lib/Drupal/Component/DependencyInjection/C" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "eclkc.ohs.acf.hhs.gov"
```

**Comment by eeeady** [comment]
Checking on the mariadb instance it looks like there was a cpu spike at about that same time however... its still only at 66% utilization
![Screen Shot 2021-08-01 at 7 51 16 AM](https://user-images.githubusercontent.com/1760850/127775317-3210bcc4-0c4c-475e-9202-533fac5f2b21.png)

**Comment by eeeady** [comment]
restarted php since that looked dead.

**Comment by eeeady** [comment]
restarted mariadb and we're back

**Comment by eeeady** [comment]
max_connections is set to 400. going to up that.

**Comment by eeeady** [comment]
We're back.. I think we need to do a deepdive on the db this week
