### ISSUE TITLE
Nagios Alert: paradiso.east.eclkc/Disk Check is CRITICAL

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#160]
Receiving Nagios alert about disk on paradiso server every hour since 7/31 10:12PM ET

***** Nagios *****

Notification Type: PROBLEM

Service: Disk Check
Host: paradiso.east.eclkc
Address: 10.0.0.168
State: CRITICAL

Date/Time: Sat Jul 31 22:12:49 EDT 2021

Additional Info:

DISK CRITICAL - free space: / 8743 MB (5% inode=94%):

Need to investigate and fix.

Our assumptions at this point:
* Static files being uploaded
* They've reached a size threshold
* We will be able to fix either by deleting resources or increasing disk space.
* What are the consequences of increasing disk space elsewhere in the system (i.e. if we are taking snapshots every night and keeping them forever)? So consider retention and snapshot.

Likely this will include reaching out to iPD team  and confirming whether they need all resources.

AC:

- [ ] Paradiso server no longer triggers Nagios alerts every hour for disk check

**Comment by jerels** [comment]
[BLOCKED] waiting to free up space during the maintenance window on 8/19

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
