### ISSUE TITLE
Root Cause Analysis for Site Outage on 08/01/2021

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#161]
We need to document a Root Cause Analysis for the intermittent outage that occurred on 08/01/2021.

See https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/159

See slack: https://trussworks.slack.com/archives/C01T6F5PB1A/p1627826552012700?thread_ts=1627826544.012600&cid=C01T6F5PB1A

Use this template: https://docs.google.com/document/d/1ovcHH9yvhJUVog1tUp8XwrXBxKrbrOZs5CDgM9EciUs/edit

AC:

- [ ] Root Cause Analysis documented
- [ ] Tickets created if needed or existing tickets tagged as needed

**Comment by eeeady** [comment]
https://docs.google.com/document/d/1_wjKqB4kfogJ3aBNmZFxsl6ZHtWKKyTSXQ31Qq6Y6Gk/edit#bookmark=kix.a743yo241zcn

@kilbergr Who did you send the last one to? I wanna make sure I get the whole list.

**Comment by kilbergr** [comment]
@eeeady Alana, ryan.ahearn@gsa.gov, jessica.dussault@gsa.gov, Scott, Sanjay

**Comment by eeeady** [comment]
Sent!
