### ISSUE TITLE
Notification templates for hosting system

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#162]
As a team, we need to follow common standards when we send out messages to our stakeholders about system incidents so that the On Call Communicator doesn't have to figure out how to write the message every time.

We will need templates for the following messages:
1. Initial Report
2. Intermediate Updates
3. Resolution

We also need to handle different types of incidents:
1. Security
2. Full Outage
3. Partial Outage

AC:

- [ ] Templates for each type of message available in GitHub

**Comment by ssatagopan** [comment]
@nateprice18f could you review and accept? since i worked on them, didn't feel like i should close.

**Comment by nateprice18f** [comment]
Looks great, closing.
