### ISSUE TITLE
Ideal State Architecture Diagram

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#167]
For the upcoming CFT meeting for ATO submission, we will need to describe our vision for the system moving forward so that we can inform the stakeholders and then determine what we can get done based on the time given.

A high level architecture diagram will help communicate this effort along with some documentation about the different use cases supported.

This ticket is for the architecture diagram only. There will be a follow up for the descriptive text and other documentation.

AC:

- [ ] High level diagram illustrating ideal hosting environment system

**Comment by eeeady** [comment]
@ssatagopan I've added the generic ideal state as a draft in the Drawio document we had the WIP eclkc architecture in...

here's a copy of it here 
![WIP  ECLKC architecture-OHS Hosting - Future State high level](https://user-images.githubusercontent.com/1760850/128269812-61628f99-d77f-437e-85d5-2cbcef8ccda1.png)

**Comment by ssatagopan** [comment]
Only comment for me is that it would be helpful to represent app separation or consolidation in diagram.

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
