### ISSUE TITLE
ECLKC site down

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#170]
## Reported By
UptimeRobot

## Application Context
ECLKC

## Environment Context
Prod

## Describe the issue
UptimeRobot reported site down at 2:41AM ET.

The site is showing a 404:

## Impact
* All users

### Reproducibility
Always

### Steps to reproduce the behavior:
1. N/A

## Expected Behavior
Site up

## Screenshots
![image](https://user-images.githubusercontent.com/13230145/128162076-3529af7b-b679-4df6-bf8f-08a7e0abbfd2.png)

## Additional Context
Could be related to penetration testing again

**Comment by uwohscc** [comment]
Issue #168 has the solution that I put together yesterday.

**Comment by samu711** [comment]
<img width="659" alt="Screen Shot 2021-08-04 at 10 14 57 AM" src="https://user-images.githubusercontent.com/17690417/128197064-5fd42461-a858-475b-97f8-918dcde4719d.png">
 You should probably change the db credentials.

**Comment by uwohscc** [comment]
Sorry: it is not that. Just read issue #168.

Dayton Allemann

**Comment by samu711** [comment]
We need to restart the MariaDB to restore the service.

**Comment by uwohscc** [comment]
It will just crash again. Pull the most recent code, restore the db to Aug.
1st, then start Mariadb again. Theoment it starts, alert me so I can add
the new quarantine role-id to the db.
Read issue #168.


Dayton Allemann

**Comment by samu711** [comment]
Oh, I didn't know that CC was on the same database instance. I was thinking about the rest of the applications. I can disable CAS access to CC and restart the db, so we have the other applications up while actions are taken in CC.

**Comment by jduss4** [comment]
@eeeady restarted mariadb and the site is back up for the moment

**Comment by uwohscc** [comment]
I may be speaking out of turn here, but I think it is important:
Stopping CAS access to the CC will not work because once a session has been started, CAS is not asked for validation again; only on login.

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
