### ISSUE TITLE
Jenkins Task fail on https://stage.eclkc.info/cc/

### ISSUE THREAD

**Issue by uwohscc** [OHS-Hosting-Infrastructure/infrastructure#174]
## Reported By
Dayton Allemann daytonra@uw.edu

## Application Context
Staging site for Coaching Companion

## Environment Context
Staging

## Describe the issue
The Jenkins Task which pulls the ohscc repo to https://stage.eclkc.info/cc/ after a push to the repo, is failing. I receive a report when this fails, and I have added that here under ## Additional Context.

## Impact
HSCC developers
* How many are affected?
Basically just me, but I can't test new code when this task fails

### Reproducibility
Always

### Steps to reproduce the behavior:
Go to:  https://jenkins.eclkc.info/job/GitHub-OHSCC/647/display/redirect
Check the change log.

## Additional Context

See <https://jenkins.eclkc.info/job/GitHub-OHSCC/647/display/redirect>

Changes:

------------------------------------------
Started by user rkilberg_dev
Running as SYSTEM
Building in workspace <https://jenkins.eclkc.info/job/GitHub-OHSCC/ws/>
using credential cb35199d-f217-48e4-a720-4bc865d8cd35
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/HSICC/OHSCC # timeout=10
Fetching upstream changes from https://github.com/HSICC/OHSCC
 > git --version # timeout=10
using GIT_ASKPASS to set credentials
 > git fetch --tags --progress -- https://github.com/HSICC/OHSCC +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 7e438e5ab6fdc7b56b2414595c779e52bc64ac50 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 7e438e5ab6fdc7b56b2414595c779e52bc64ac50 # timeout=10
Commit message: "post ECLKC outage adjustments at 2021-08-04 at 16:55:41"
 > git rev-list --no-walk 7e438e5ab6fdc7b56b2414595c779e52bc64ac50 # timeout=10
[SSH] executing pre build script:

[SSH] executing post build script:
PATH="/sbin:/usr/sbin:/bin:/usr/bin"

REPOPATH='/var/www/ohscc/cc'
STASH=0

cd $REPOPATH

stash_pop()
{
  if [ $STASH == 1 ]; then
    echo "Popping stash"
    git stash pop
  fi
}

if [ ! 'git status --porcelain' ]; then
  echo "Stashing changes"
  git status | mailx -s "Unstaged changes found at $(pwd)" -S replyto="jenkins@eclkc.info" kyle@cleverex.com
  git stash
  STASH=1
fi

# make sure to update references with fetch
if ! git fetch --all; then
  stash_pop
  exit 1
fi

if ! git pull origin master; then
  # pop stash before exiting for git failure
  stash_pop
  exit 1
fi

stash_pop

From github.com:HSICC/OHSCC
 * branch            master     -> FETCH_HEAD
Fetching origin
error: The following untracked working tree files would be overwritten by merge:
        vce-content/components/nestor_reports2BAK/css/progress_bar.css
        vce-content/components/nestor_reports2BAK/css/style.css
        vce-content/components/nestor_reports2BAK/example_summaries/example_summaries.php
        vce-content/components/nestor_reports2BAK/images/loading_38.gif
        vce-content/components/nestor_reports2BAK/images/loading_large.gif
        vce-content/components/nestor_reports2BAK/index.php
        vce-content/components/nestor_reports2BAK/js/jquery.ui.touch-punch.min.js
        vce-content/components/nestor_reports2BAK/js/script.js
        vce-content/components/nestor_reports2BAK/nestor_report_summaries_state/nestor_report_summaries_state.php
        vce-content/components/nestor_reports2BAK/nestor_reportsBAKold.php
        vce-content/components/nestor_reports2BAK/nestor_reportstype/nestor_reportstype.php
Please move or remove them before you can merge.
Aborting
Updating 02574b5..7e438e5

[SSH] completed
[SSH] exit-status: 1

**Comment by kilbergr** [comment]
Let's check this after this: https://github.com/orgs/OHS-Hosting-Infrastructure/projects/1#card-66337294 is complete to see whether there's still an issue.

**Comment by uwohscc** [comment]
Thanks!

**Comment by uwohscc** [comment]
Hi!  This issue still needs to be resolved; I can't access one of the core configuration pages on the staging site because the staging site has old directories in it which are not in the Github repo. This makes the staging site useless at the moment.

Please let me know if we can set up a timeline for fixing this. Thanks!

**Comment by ssatagopan** [comment]
@uwohscc We don't have a timeline but have it on tap after we set up our current monitoring and Lifeboat switching work.

**Comment by uwohscc** [comment]
Thank you!

**Comment by eeeady** [comment]
Tried cleaning up everything that wasn't tracked in git. @uwohscc can you see if that's cleaned up what you need?

**Comment by uwohscc** [comment]
I believe that this did the trick. I can access all the admin pages which were broken before, and I can add and delete files and folders and they are also deleted from the staging instance after a push to Github.
So: thank you! Everything is working.
