### ISSUE TITLE
Update CC Staging env to most recent version

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#176]
Deploy Dayton's changes to HSCC staging to fix this issue: https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/171

We were able to deploy the changes Dayton had made to prod for CC, but the deployment process for staging was different so we didn't do a deploy because Dayton said it was secondary. Let's get back in there and finish this work!

AC:

- [x] CC staging (apparently on the coachingcompanion-dev server) is up to date.
- [x] Update [the CC deployment runbook](https://github.com/OHS-Hosting-Infrastructure/infrastructure/pull/172) with instructions

**Comment by eeeady** [comment]
I'm looking at the machine anyways... I'll take this

**Comment by eeeady** [comment]
did a hard reset to what origin had and then had to go fix the jenkins job. This was using an old auth method to github, updated to use a different set of api keys.
