### ISSUE TITLE
[User Request] Change demo server URLs

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#177]
## Requested By
@samu711 

## Application Name
ECLKC

## Purpose
CAS cannot handle the hyphen in the demo server URLs so they need to be update to enable CAS to connect properly

## Description of this Change
CAS cannot handle the hyphen in the demo server URLs so they need to be update to enable CAS to connect properly

* _Is this change a configuration change or a software change?_
* _Does this change require data schema migrations?_
* _Does this change fix a security vulnerability?_
* _What is the expected outcome and behavior?_

## User Impact
HSICC team

## Timeline
No expected timeline

## Blocked by 
https://github.com/OHS-Hosting-Infrastructure/environment-configuration/issues/80

## Acceptance Criteria
- [ ] CAS can connect to demo servers
- [ ] Demo server URLs are set to eclkcdemo1.eclkc.info, eclkcdemo2.eclkc.info, and eclkcdemo3.eclkc.info

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
