### ISSUE TITLE
[Maintenance] Drupal ECLKC Release for 06/15?

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#18]
This is the regularly scheduled ECLKC Drupal release

Add any additional changes we need to perform during this window here:

- [ ]

**Comment by ssatagopan** [comment]
@eeeady Can this be closed?

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
