### ISSUE TITLE
Onboard Nate, access to all the systems

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#184]
Our new team member, Nate, needs access to our systems. Should be roughly similar to Jessica and Ryan's access.

Follow this guide:
https://github.com/OHS-Hosting-Infrastructure/infrastructure/blob/main/docs/runbooks/onboard-a-new-hosting-team-member.md

AC:

* Nate has access to GH, AWS, SSH, and VPN.

**Comment by kilbergr** [comment]
From Jessica:
Invite Nate to the following: 

Truss specific
Daily Standup 1pm:  M, T, W, R
Sprint Grooming 1pm: M
Sprint Retro and Planning 12pm - 1:30 pm T
Strategy / sync 2pm: R
Team Retro 4pm: F

Truss + Pals
ECLKC/TA technology 2pm: M
IPT (ATO) 12pm: T
Hendall + Truss 1pm: W

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
