### ISSUE TITLE
[High] Update Apache httpd PROD

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#186]
Need to update Apache httpd on the following servers:
* ParadisoLMS-autoscaling

For more details, see latest [OS scan results](https://app.box.com/folder/143269631989?s=8l7r7h0s2isferfxacyhgra8u869kwsp).

More info at Apache - https://httpd.apache.org/security/vulnerabilities_24.html

AC:
- [ ] Apache httpd is updated to 2.4.48
- [ ] After changes, security scan does not find same vulnerabilities on server

**Comment by kilbergr** [comment]
Heads up -- you can id by using the command `apache2 -version` (I had been running `apache -version` or `httpd -version`.

**Comment by ssatagopan** [comment]
Scan did not find vulnerability associated with apache httpd on new paradiso prod instance
