### ISSUE TITLE
[User Submitted] Issues seen by users of ECLKC after caching changes on 8/17/21

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#193]
## Reported By
Sam Nevares (@samu711)

## Application Context
ECLKC

## Environment Context
Prod

## Describe the issue
As a consequence of the configuration changes implemented on 8/16/21 to mitigate the load on the servers, users are facing multiple problems while navigating the site. Most of them are related to broad Cloudfront cache policy. It looks like the cache is based solely on the URL Path and ignores the query parameters and the cookies.

## Impact
* Users of ECLKC
* Numerous

### Reproducibility
Frequently

## Expected Behavior
Pages load as expected

**Comment by eeeady** [comment]
@samu711 Switched to a caching policy that includes cookies and query strings. Is there a way we can test that this fixed it?

**Comment by samu711** [comment]
Bhuvan did the testing and most of the issues are solved. Thanks, this was very useful!
