### ISSUE TITLE
[High] CentOS Security Update for java-1.8.0-openjdk Security Update (CESA-2021:2845)

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#195]
Latest security scan resulted in vulnerability found for following servers:
- IDS-Logs
- Ansible-Nagios
- VPN
- Jenkins
- Solr
- MariaDB
- LDAP
- LifeboatDB
- MobileApp-Locator
- Lifeboat
- Tomcat2
- Tomcat1
- InjuryIllness
- Varnish2
- Varnish1
- CoachingCompanion

Vulnerability:
CentOS Security Update for java-1.8.0-openjdk Security Update (CESA-2021:2845)

Solution:
To resolve this issue, upgrade to the latest packages which contain a patch. Refer to CentOS advisory >[centos 7](https://lists.centos.org/pipermail/centos-announce/2021-August/048348.html) for updates and patch information.

See latest [scan results](https://acf-headstart.box.com/s/8l7r7h0s2isferfxacyhgra8u869kwsp) in Box for more information.

AC:

- [ ] Patch applied to affected servers
- [ ] Scan doesn't find same vulnerability on same servers after update is applied

**Comment by eeeady** [comment]
Looked at the scan results. It looks like we need to update the patch level. We should still try this on Staging first.

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
