### ISSUE TITLE
Intermittent 404 on ECLKC on 8/18 11:55PM ET and 8/19 5:41AM ET

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#197]
Received Uptime Robot messages about ECLKC being down with 404 error at 11:55PM ET on 8/18. It came back in < 5 minutes.
Received another message with 404 at 5:41AM ET on 8/19. Again, it came back in < 5 minutes.

Didn't see any blocked requests at the time due to rate limiting.

When looking at amount of requests in WAF monitoring, nothing excessive, but I do see repeated spikes of requests every 3 hours, not sure what that is:
![image](https://user-images.githubusercontent.com/13230145/130067605-91a1907c-83b7-4969-a39e-87a76ccace08.png)

Ticket is for monitoring and investigation if it persists.

AC:

- [ ] Investigation of 404 and results documented
- [ ] Tickets created for follow up actions if applicable

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
