### ISSUE TITLE
[Technical Research] Base AMI

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#20]
What is our recommendation for OS and what are the base applications we need installed?

Outcome:
- [ ] A base AMI or example AMI build/template to give to application teams to build upon
- [ ] Expect to move off Centos (likely to Ubuntu or Amazon Linux)

AC:
- [ ] An ADR with a design for basics that go in an AMI
- [ ] An example AMI build/template

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
