### ISSUE TITLE
Coaching Companion goes down for at least 20 minutes during maintenance windows.

### ISSUE THREAD

**Issue by uwohscc** [OHS-Hosting-Infrastructure/infrastructure#201]
## Reported By
Dayton Allemann daytonra@uw.edu

## Application Context
Coaching Companion

## Environment Context
Production

## Describe the issue
During the past two maintenance windows, the Coaching Companion site is unavailable for over 20 minutes and displays this error:
Error 503 Backend fetch failed
Backend fetch failed

Guru Meditation:
XID: 361481

Varnish cache server

## Impact
All users

### Reproducibility
During maintenance window, try to access the CC

## Additional Context
I tried to get in touch with anybody at Truss about this the last time it happened; this is a big issue. The only response I got is that it was caused by the maintenance window procedures.  Let me know what to expect here; if we are to have down-time and no "Server In Maintenance" type landing screen, I need to know this!

**Comment by eeeady** [comment]
@uwohscc I'm really confused. The maintenance window process has not changed from the old Sevatec team and as far as we knew there was no documented server maintenance landing screen for Coaching companion. If you would like to use one we can work together to stand one up during maintenance windows.

**Comment by uwohscc** [comment]
Hi! I checked the status of the site to see how long the problem persisted; it was more than an hour but less than two hours. 

Looking back through my notes, this did happen a couple of times during Cleverex maintenance windows. I never got a description from them about what caused it. At those times, I contacted Cleverex and they solved it quickly, as if it were an oversight which had a simple solution. This is just conjecture on my part, however.

Other than knowing that this is Varnish telling us that the server is unavailable, I don't have enough information to know what has been causing the outage.

**Comment by uwohscc** [comment]
The most important thing for me to know about this problem is this:  is it planned that the server becomes unreachable? Looking back at Elizabeth's comment, I might be reading it the wrong way. Were you surprised that the server went down, or surprised that I found that unusual? Up until the past two maintenance windows, I was not aware of any problems that could or should constitute an interruption of service.

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
