### ISSUE TITLE
iPD 503 Backend Fetch Error

### ISSUE THREAD

**Issue by bkingztt** [OHS-Hosting-Infrastructure/infrastructure#202]
## Reported By
Brittany King (bking@zerotothree.org)

## Application Context
iPD

## Environment Context
Production

## Describe the issue
503 Backend fetch error

## Impact
Everyone

## How To Reproduce
Log in to the iPD.

### Reproducibility
Always

## Screenshots
<img width="1419" alt="Screen Shot 2021-08-20 at 8 28 34 AM" src="https://user-images.githubusercontent.com/88720340/130233859-0bae4532-5200-4107-ba8c-b56259337d09.png">

## Additional Context
We had a maintenance window last night

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
