### ISSUE TITLE
Initial System Design Doc for new OHS Hosting infrastructure

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#207]
We need a System Design document for the new OHS Hosting infrastructure so that it can be reviewed as well as documented as part of our ATO process.

The expectation is that the document will cover the high level design for building the new system in AWS us-west using a single user with the intent of moving Head Start Coaching Companion to that new infrastructure as a trial.

This expectation is different from the ideal design because:
* it is using a single AWS user account
* it does not include CAS so it will not allow full functionality of the Coaching Companion application

AC:
- [ ] System Design document in OHS-Hosting-Infrastructure/infrastructure/tree/main/docs/design-docs
- [ ] Document is understood by team and reviewed by team, 18F, and application team engineering leads

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
