### ISSUE TITLE
Sam added to PagerDuty and included in schedule

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#208]
As part of helping the Truss team support ECLKC, Sam needs to be included in PagerDuty and included in the schedule so that he can be alerted during this on-call hours and can escalate to Truss if needed.

Sam's email: samuel.nevares@hendall.com

AC:
- [ ] Sam added as a user to headstarthosting PagerDuty account
- [ ] Sam included in rotation based on his on-call hours of 7AM ET - 11AM ET every weekday

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
