### ISSUE TITLE
Maintenance pages for iPD and CC

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#209]
During maintenance or outages when ECLKC is switched over to Lifeboat, iPD users and CC users do not receive any messages when they try to access. We need to provide a message shown to those users when site is on Lifeboat so that they can understand what's going on.

Sample text:
"iPD Portfolio is currently undergoing maintenance and should be available in a few hours. We apologize for the inconvenience."

AC:
- [ ] When site is using Lifeboat, maintenance page is shown when user navigates to iPD
- [ ] When site is using Lifeboat, maintenance page is shown when user navigates to Coaching Companion

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
