### ISSUE TITLE
Create a jenkins job to restart MariaDB server

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#210]
As part of including Sam in our support team, we need to create a way for him to restart the MariaDB server when needed.

The suggestion is to create a Jenkins job/script to restart MariaDB.

AC:
- [ ] Able to restart MariaDB server from Jenkins
- [ ] Runbook available for procedure

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
