### ISSUE TITLE
Create email trigger to PagerDuty

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#211]
We need a way for the application teams to trigger PagerDuty alerts when something happens that is not detected by our existing Cloudwatch triggers.

The proposal is to have an email address that the application teams can send an email to that then triggers an alert in PagerDuty.

AC:
- [ ] PagerDuty configured to have email trigger alerts

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I have closed all open issues with a script, including this one.
