### ISSUE TITLE
[User Submitted] headstart@eclkc.info mailbox for user is full

### ISSUE THREAD

**Issue by samu711** [OHS-Hosting-Infrastructure/infrastructure#212]
Mail Inquiries
Mail Server

## Environment Context
Production

## Describe the issue
headstart@eclkc.info is the main mail account used to receive user general inquiries. When the user sends an inquiry to this mail box they get the following message:

Your message to <headstart@eclkc.info> was automatically rejected:
Quota exceeded (mailbox for user is full)

The message is still received in Mail Inquiries though.

## Impact
Users and Customer Center

## How To Reproduce
Send an email to headstart@eclkc.info

## Expected Behavior
Not to receive this message.

**Comment by ssatagopan** [comment]
From @eeeady: 

Alright. I was able to clear out the mail box

 

I had to ssh to the machine and as root do some doveadm commands

`doveadm mailbox list -u headstart@eclkc.info`

will show you the folders in the mailbox for the user

I used the following commands to clean up obvious stuff from the mailbox:

`doveadm expunge -u headstart@eclkc.info mailbox Junk all`

Cleans junk

`doveadm expunge -u headstart@eclkc.info mailbox Trash.'*' before 1w`

Cleans anything older than a week from trash sub folders 

`doveadm expunge -u headstart@eclkc.info mailbox Trash before 1w`

Cleans anything older than a week from trash folder

`doveadm quota get -u headstart@eclkc.info`

will show you the quota limits for the user

`doveadm quota recalc -u headstart@eclkc.info`

will recalculate quota limits for the user (this will need to be run after you clean up old junk

 

For reference, I used https://support.plesk.com/hc/en-us/articles/115002372774-How-to-delete-all-or-some-emails-from-a-mailbox-without-logging-in-to-the-mailbox-
