### ISSUE TITLE
[Technical Research] VPN cost analysis

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#23]
- Do a little research and determine if we should keep running out own VPN server or move to AWS's Client VPN solution.
  - note cost and then also take into account user experience and operational overhead

Outcomes:
- [ ] The hosting team should know whether or not to continue investing in the existing VPN service or what to replace it with

AC:
- [ ] ADR describing whether we should continue using the existing openvpn server or move to AWS managed vpn

**Comment by rahearn** [comment]
If I'm reading the [client VPN pricing](https://aws.amazon.com/vpn/pricing/) correctly then I think actually running EC2 instances is more cost effective (based purely on servers) than the Client VPN service as long as the EC2 instances are smaller than `.xlarge`

The open question I have is whether the "endpoint association" charge is charged 24/7 once there is an option to connect to the VPN, or if it's only charged if anyone is currently connected.

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
