### ISSUE TITLE
[Technical Research] Managing users in IAM

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#24]
Review existing:
- groups
- Policies
- Enforce MFA
- clean out old users if necessary

Terraform groups, policy access, and user groups.

Create these things based on newly documented access control policy.

Write guidance for automation access (policies for lambdas/ec2 instances etc and robo users for ci).

AC:
- [ ] Create tasks for making appropriate terraform modules
- [ ] Create new user access

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
