### ISSUE TITLE
[Technical Research] Manage relational databases

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#26]
Outcome:
- [ ] Headstart hosting has a well thought out offering for managing relational databases. Please answer the following questions:
  - Do we co-host multiple databases on the same RDS instance?
  - How do we manage backups? Can we restore? What is our retention policy?
  - How do we make it easy for folks to integrate with the RDS instances? How can the devs access them?
  - How do we ensure the security of the data stored in our databases? 

AC:
- [ ]  A product(?) spec and stories for smaller slices of this work

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
