### ISSUE TITLE
[Automation] Swapping traffic to lifeboat

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#27]
This is outlined as part of the SOP for both Drupal deploys and Monthly maintenance.

The process is roughly:
1. sync data from prod to lifeboat
2. direct traffic from prod to lifeboat
3. cycle out any lingering connections to prod

We should also be able to switch back.

AC:
- [ ] A design doc for how to automate this.

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
