### ISSUE TITLE
[Maintenance] Monthly Maintenance for June 24, 2021

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#28]
Regularly scheduled maintenance.

Additional changes
- [ ] https://docs.google.com/document/d/1D5Re5sgyNFJYRP1ZV3k-CuqzxXfcnmU1uOzizSRQjmQ/edit
- [ ] https://github.com/orgs/OHS-Hosting-Infrastructure/projects/1#card-63516004

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
