### ISSUE TITLE
[HELP] ECC Access to existing systems

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#29]
EEC needs to be upgraded from Drupal 7 -> Drupal 9 before the end of Sept. This is being handled by ICF and our point of contact is Dan Gorman.
- [x] Get developer user info from Dan Gorman
- [ ] Answer from ACF if we can give them production access to the currently deployed system and the requirements there.

For each user:
- [ ] Add users to github org
- [ ] Email users: get VPN certs and public keys set up for dev/staging machines

**Comment by dan-gorman-ICF** [comment]
1. Brian DeAngelis: brian.deangelis@icfnext.com (briand617)
2. Avani Mehta: avani.mehta@icfnext.com (avaniicf)
3. Lera Atwater: lera.atwater@icfnext.com (LeraAtwater)

**Comment by dan-gorman-ICF** [comment]
4. Carey Hartmann: carey.hartmann@icfnext.com (icf-chartmann)

**Comment by dan-gorman-ICF** [comment]
@eeeady could you please confirm the current Staging environment URL for EEC? I have the Production URL: https://earlyeducatorcentral.acf.hhs.gov/

**Comment by eeeady** [comment]
Sorry for the delay. I at least sent out all of the invites to github.

As far as the staging environment.... I'm actually not sure what the staging environment url is.

**Comment by eeeady** [comment]
FOUND THE ALB ecc-dev-eclkc-info-2004718544.us-east-1.elb.amazonaws.com but it looks pretty broken.

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
