### ISSUE TITLE
Create SSH access for EEC Developers

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#32]
The following developers need SSH access

Brian DeAngelis: brian.deangelis@icfnext.com (briand617)
Avani Mehta: avani.mehta@icfnext.com (avaniicf)
Lera Atwater: lera.atwater@icfnext.com (LeraAtwater)
Carey Hartmann: carey.hartmann@icfnext.com (icf-chartmann)

Follow instructions to grant SSH access here:
XXXX

AC:
All 4 devs mentioned above have confirmed SSH access.

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
