### ISSUE TITLE
ADR for how to manage individual ssh access for users

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#33]
We are giving more individual access to devs. We should be able to track commands and access back to specific users.

Outcome:
- [ ] Users know what to expect from SSH access
- [ ] Hosting team knows how to configure SSH access to machines

AC:
- [ ] Write an ADR that outlines the strategy, technical methodology, and what we provide 
- [ ] Spin out tickets for: documentation for users, adding new users

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
