### ISSUE TITLE
Monthly Maintenance window [05/20]

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#4]
Regularly scheduled maintenance window.

Server changes:
- OS Updates

ECLKC changes:
- Node version update no the Tomcat servers. Update to version 12.
- Update google analytics config for HSICC on the EEC server
```
Replace file at
/var/www/eec/infanttoddler/web/analytics.txt
with new version provided by Sam (Eady has it for now)
```

LMS changes:
- Update crontab configuration

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
