### ISSUE TITLE
Remove Elizabeth Rivera's HHSAccountManager status and grant it to Alana

### ISSUE THREAD

**Issue by jerels** [OHS-Hosting-Infrastructure/infrastructure#46]
Currently Elizabeth Borda Rivera is the only one on with HHSAccountManager status (Billing). Seeing as our new COR is Alana, we should go about removing Elizabeth and grant access to Alana.

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
