### ISSUE TITLE
[User Request] SmartHub able to send email from their application

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#49]
As a TTA SmartHub developer, I would like to add functionality to SmartHub that can send emails out to users so that I can send notifications when workflows demand it, i.e. approvals needed for an Activity Report.

Outcomes:
* Infrastructure configured to let TTA SmartHub team send email
* Documentation on how TTA SmartHub team can use infrastructure capability
* TTA SmartHub team able to send email from their application

**Comment by ssatagopan** [comment]
Recording of meeting with TTA SmartHub team:
https://drive.google.com/drive/folders/1ipgqztdvm9o8EUpjH2IcNyVOsNr6VovP?usp=sharing

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
