### ISSUE TITLE
[ADR] Define SSM parameter store conventions

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#50]
The Hosting team and other dev teams will need to store configuration variables and secrets. For ease of use let's use SSM parameter store to be able to properly manage this configuration, we'll need to structure prefixes to allow proper IAM access.

Outcome: The hosting team is able to provide a namespace in SSM parameter store to individual teams and can lock down access to specific environments.

AC:
- [ ] A PR with an ADR outlining a prefix schema that enables environment/application level access for IAM users.
- [ ] Document for development teams what we will provide to them and how to use SSM.

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
