### ISSUE TITLE
[Technical Research] Define logging s3 bucket naming conventions

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#51]
We have inherited like... 3-4 different buckets with different kinds of logs. Please determine which bucket(s) to use for what and then the naming convention for prefixes.

You will likely want to refer to Truss' terraform module for a logs bucket here https://github.com/trussworks/terraform-aws-logs to get a sense of what logs we will likely store in this bucket.

Do NOT use this bucket for bucket access logging.

Please make it relatively simple to isolate logs between dev/stage/prod environments.

Outcome: We have standard convention for how to name/prefix logs in AWS buckets.

AC:
- [ ] A PR with an ADR that defines which logs bucket(s) to use
- [ ] Documentation for how devs should use and review logs in s3buckets

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
