### ISSUE TITLE
Cycle out cert for eclkc.ohs.acf.hhs.gov

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#52]
The certificate for eclkc.ohs.acf.hhs.gov is expiring on 7/16. Please send an email to the appropriate ACF helpdesk to initiate this request on the week of 07/04.

=== Historical context below ===

the cert for eclkc.ohs.acf.hhs.gov will expire in 78 days- reach out to renew
Update 05/12 -
Sent information to Dela so we can get started.

Update 05/19 - Followed up with Dela.

Update 06/04 - Checked with Dela- She thinks it should only take a few days to renew but scheduled a meeting with our team for next wednesday to chat.

update 06/09 - Call with Dela and team. Need to email the right team tto ask for a renewal.

**Comment by kilbergr** [comment]
@eeeady looks like this was done. Can I close this ticket?

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
