### ISSUE TITLE
[User Submitted] Head Start locator iFrame not working when embedded into other sites [1pt]

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#62]
## Reported By
Sam Nevares (HSICC) - Samuel.Nevares@hendall.com
Julie Stone (OHSAI) - stone@ohsai.org

## Application Context
ECLKC

## Environment Context
Production

### Original report from Julie Stone:
I am the Associate Executive Director of the Ohio Head Start Association. We had
code to embed on our association webpage but it's not linking anymore. 
See bottom right corner of www.ohsai.org
It looks broken and says eclkc.ohs.acf.hhs.gov refused to connect
### Details from Sam:
Some users are reporting that the ECLKC center locator page (I think it’s our top visited page) embedded on their sites is no longer available. This is because we recently added a Content Security Policy to our Varnish servers to only allow https://acf.hhs.gov and https://*.acf.hhs.gov to load some of our pages in iframes. In order to solve this problem we need to update the Varnish configuration in production to update all these third party sites. We can’t fully test this approach in staging as all the third party sites just point to our production page.

The varnish config files (Varnish1 and Varnish2) are located in /etc/varnish/default.vcl of each server (they are different in V1 and V2). I’ve left an updated file in the /home/drupal folder of each of the servers. After updating the configuration files we’d need to restart the varnish servers, there’s a job in Jenkins for that.

Could we plan to apply this change as soon as possible due to the impact that this page has?

 Basically we’re replacing this line:

```
diff --git a/default.vcl b/etc/varnish/default.vcl
index f67de64..e2866ca 100644
--- a/default.vcl
+++ b/etc/varnish/default.vcl
@@ -562,7 +562,7 @@ sub vcl_deliver {
req.url ~ "^/JBTraq1/JBTraqServlet" ||
req.url ~ "^/foa-condensed") {
unset resp.http.X-Frame-Options;
+      set resp.http.Content-Security-Policy = "frame-ancestors 'self' *.hhs.gov *.benefits.gov *.nhsa.org *.nmshsa.org georgiaheadstart.org *.catholiccharitiesaz.org saheadstart.org *.saheadstart.org mnheadstart.org houstoncasemanagers.com *.houstoncasemanagers.com *.chicagoabortionfund.org *.headstartva.org *.ne.gov *.ohsa.net *.alaska.gov wsaheadstarteceap.com tnheadstart.info *.alabama.gov buildearlyed.org *.greeleyschools.org *.txhsa.org *.ctoec.org *.stepincva.com *.md-hsa.org *.southern7.org *.hsuniversity.org msheadstart.org *.marc.org headstartky.org *.jumpstart-finance.com ohsai.org";
-      set resp.http.Content-Security-Policy = "frame-ancestors 'self' https://acf.hhs.gov https://*.acf.hhs.gov";
     } else {
```

## Impact
* End users who are trying to use the Head Start locator embedded in a different site
* Lots

### Reproducibility
Always (in other sites)

### Steps to reproduce the behavior:
1. Go to 'https://ohsai.org/'
2. Scroll down to bottom right where it says "Ready to Enroll a Child? Find a Provider"
3. Observe that the square area with locator is broken and shows message "eclkc.ohs.acf.hhs.gov refused to connect"

## Expected Behavior
Locator should look like what's in this page:
https://eclkc.ohs.acf.hhs.gov/center-locator/embedded

## Screenshots
![image](https://user-images.githubusercontent.com/13230145/122766319-5f7a8580-d26f-11eb-8e3f-e96b83a68bb8.png)

## Acceptance Criteria

* When you go to this page: https://ohsai.org/, bottom right where it says "Ready to Enroll a Child? Find a Provider" has working plug in.

**Comment by eeeady** [comment]
Applied this change manually on 06/24/2021 maintenance window

**Comment by eeeady** [comment]
![Screen Shot 2021-06-24 at 6 00 23 PM](https://user-images.githubusercontent.com/1760850/123353304-139d3a00-d516-11eb-9a3d-e9b54a3a1dfc.png)
works!
