### ISSUE TITLE
Grant HSICC Team VPN access [3Pt]

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#63]
We need to allow HSICC team VPN access so they can get onto hosted systems. We were going to try to follow a new process, but have decided to follow the old process to speed things along.

Here are the names of the folks we need to grant access to:

- Bhuvan Neupane bhuvan.neupane@hendall.com
- Raul Rodriguez rrodriguez@jbsinternational.com
- James Donovan jdonovan@jbsinternational.com
- Matthew Starr mstarr@jbsinternational.com
- Ty Collington ty.collington@hendall.com

We need to get CSRs from each of them.

Send an email to each team member, asking whether they're using Mac or Windows, what version, and what VPN they're using.

Document this information, and write a proposal of which VPN we recommend using with Windows. 

AC:

* How to document for Windows users to select and download recommended VPN.
* Update the existing tickets to onboard each user. It should contain their OS, their VPN, and their email. 
* [ ] Tell HSICC and anyone else that does this frequently.

**Comment by eeeady** [comment]
Chatted with Sam. Most of the team uses Windows. We'll need to create instructions for windows users.

**Comment by kilbergr** [comment]
:/ Time to create a new ticket! Could you create a ticket with that requirement so we can pull into our sprint tomorrow?

**Comment by samu711** [comment]
VPN access for Monika Rallabandi is not needed anymore.

**Comment by samu711** [comment]
We also need VPN access for Ty Collington (ty.collington@hendall.com)

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
