### ISSUE TITLE
Grant VPN access for Raul Rodriguez

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#64]
We need to grant Raul access to our VPN.
This is Raul's VPN username: rrodriguez
This is Raul's email: rrodriguez@jbsinternational.com
This is the hosting team's email: headstart-hosting@truss.works. 

Schedule a zoom session to set up.
If Raul uses a Mac, you can use these instructions: https://github.com/OHS-Hosting-Infrastructure/infrastructure/pull/13/files?short_path=13c8247#diff-13c8247c31564699557a3453ead8cbe2c9ed1abd93c3e1829fc8d3021332a3cb
If Raul uses Windows, use these instructions: 
https://github.com/OHS-Hosting-Infrastructure/infrastructure/blob/main/docs/runbooks/vpn-access-requests.md
You can convey creds via this tool: https://secrets.rcahearn.net/

AC:
* Raul has VPN access

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
