### ISSUE TITLE
We need to grant Bhuvan access to our VPN.

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#66]
This is Bhuvan's VPN username: bneupane
This is Bhuvan's email: Bhuvan Neupane bhuvan.neupane@hendall.com
This is the hosting team's email: headstart-hosting@truss.works.

Blocked somewhat by: https://github.com/orgs/OHS-Hosting-Infrastructure/projects/1#card-60043672

Schedule a zoom session to set up.
If Bhuvan uses a Mac, you can use these instructions: https://github.com/OHS-Hosting-Infrastructure/infrastructure/pull/13/files?short_path=13c8247#diff-13c8247c31564699557a3453ead8cbe2c9ed1abd93c3e1829fc8d3021332a3cb
If Bhuvan uses Windows, use these instructions:
https://github.com/OHS-Hosting-Infrastructure/infrastructure/blob/main/docs/runbooks/vpn-access-requests.md

You can convey creds via this tool: https://secrets.rcahearn.net/

AC:

* We have instructions for Windows users to get onto a VPN
* Bhuvan has VPN access
* Update Bhuvan's team members' tickets to reflect the instructions that result from this ticket.

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
