### ISSUE TITLE
Grant Monika VPN access

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#68]
We need to grant Monika access to our VPN.

This is Monika's VPN username: mrallabandi
This is Monika's email: mrallabandi@jbsinternational.com
This is the hosting team's email: headstart-hosting@truss.works.

Schedule a zoom session to set up.
If Monika uses a Mac, you can use these instructions: https://github.com/OHS-Hosting-Infrastructure/infrastructure/pull/13/files?short_path=13c8247#diff-13c8247c31564699557a3453ead8cbe2c9ed1abd93c3e1829fc8d3021332a3cb
If Monika uses Windows, use these instructions:
XXXX

You can convey creds via this tool: https://secrets.rcahearn.net/

AC:

* Monika has VPN access

**Comment by samu711** [comment]
Taking out Monika from the list of users that need VPN access.
