### ISSUE TITLE
Grant Raul access to SFTP server

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#69]
Currently, despite Ryan having added his SSH key to the SFTP server, Raul appears not to have access.

Background here: https://trussworks.slack.com/archives/C01T6F5PB1A/p1623962632040700

AC:
* Raul Rodriguez has access to SFTP

**Comment by eeeady** [comment]
We were able to help Raul out by evaluating some of the SSH/SFTP troubleshooting notes from below but ultimately, he needed to decrypt his key on his keychain and wasn't being prompted by SFTP.


Notes:
# SSH/SFTP troubleshooting

## Check that the user is connecting to
- The correct domain or ip address
- That they are using the correct username. (Currently this may be shared such as sftpuser, centos, etc)
- The correct port (we are using the default of port 22)

## Also check that the user
- is connected via VPN if connecting to a 10.* address
- Has the expected private key on their ssh key chain

## Check the following configuration on our side
- Do we have the right public key on the authorized keys file on the server they are connected to?

## If they are still having trouble:
- Have they decrypted their key? Or if they have configured a password on their key, have they used the password to add the key to their ssh keychain
- Do they have several keys on their ssh keychain? Depending on the version of SSH/SFTP the client may have presented too many keys without success to the server and just die.
- Does the server have an expired certificate it is trying to present?
