### ISSUE TITLE
Write VPN instructions for Windows users

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#71]
Write up instructions for users to generate CSRs on Windows to send to the hosting team to give them access to the VPN.

The generated output must work with the current instructions:
https://github.com/OHS-Hosting-Infrastructure/infrastructure/pull/13/files#diff-13c8247c31564699557a3453ead8cbe2c9ed1abd93c3e1829fc8d3021332a3cb

**Comment by eeeady** [comment]
See https://github.com/OHS-Hosting-Infrastructure/infrastructure/pull/97

**Comment by ssatagopan** [comment]
Successfully connected to VPN on eclkc-east. There were some minor discrepancies with instructions and certmgr options and OpenVPN client, but are manageable.
