### ISSUE TITLE
[ATO] Security Controls documentation (Configuration Management)

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#81]
Need to complete Configuration Management section of [Security Controls ](https://acf-headstart.box.com/s/dzrw2lcs1gzrtxli5ngteq5vmvtealr7) document.

[Previous ATO Controls](https://acf-headstart.box.com/s/dkzxy3ojktuy00pwf7pv6clsjgruphec)

BLOCKED by:
https://github.com/orgs/OHS-Hosting-Infrastructure/projects/1#card-63180454

AC:
- [X] Configuration Management section of Security Controls filled out
- [ ] Reviewed internally and submitted to ISSO

**Comment by jduss4** [comment]
CM-01  check language (same as SmartHub ATO)
CM-02 how specific do we need to be about what is in bitbucket vs what is in github?
CM-06 may need a little attention to describe configuration documentation like Terraform
CM-07 has a note to learn more about what Semaphore is, but it was removed from the description
CM-10 *are the HSICC / app teams appropriately using licenses for software and tracking them in a spreadsheet???*
