### ISSUE TITLE
[ATO] Security Controls documentation (Planning)

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#88]
Need to complete Planning section of [Security Controls ](https://acf-headstart.box.com/s/dzrw2lcs1gzrtxli5ngteq5vmvtealr7) document.

[Previous ATO Controls](https://acf-headstart.box.com/s/dkzxy3ojktuy00pwf7pv6clsjgruphec)

AC:
- [X] Planning section of Security Controls filled out
- [ ] Reviewed internally and submitted to ISSO

**Comment by jduss4** [comment]
PL-04: Waiting on a little more information about what kind of Rules of Behavior are presented to users regardless of PIV login vs non-PIV

**Comment by ssatagopan** [comment]
Leaving as Inherited HHS
