### ISSUE TITLE
[ATO] Security Controls documentation (Risk Assessment)

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#90]
Need to complete Risk Assessment section of [Security Controls ](https://acf-headstart.box.com/s/dzrw2lcs1gzrtxli5ngteq5vmvtealr7) document.

[Previous ATO Controls](https://acf-headstart.box.com/s/dkzxy3ojktuy00pwf7pv6clsjgruphec)

AC:
[ ] Risk Assessment section of Security Controls filled out
[ ] Reviewed internally and submitted to ISSO

**Comment by jduss4** [comment]
RA-05: Are you still using OpenVAS for security scanning?

**Comment by ssatagopan** [comment]
> RA-05: Are you still using OpenVAS for security scanning?

I don't think so, think we're using Qualys. Have updated controls spreadsheet accordingly.
