### ISSUE TITLE
[ATO] Security Controls documentation (System and Services Acquisition)

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#91]
Need to complete System and Services Acquisition section of [Security Controls ](https://acf-headstart.box.com/s/dzrw2lcs1gzrtxli5ngteq5vmvtealr7) document.

[Previous ATO Controls](https://acf-headstart.box.com/s/dkzxy3ojktuy00pwf7pv6clsjgruphec)

AC:
[ ] System and Services Acquisition section of Security Controls filled out
[ ] Reviewed internally and submitted to ISSO

**Comment by jduss4** [comment]
SA-09 needs to be drafted as it did not exist in the old ATO.

**Comment by ssatagopan** [comment]
Created https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/131 to create policy document for SA-09

**Comment by ssatagopan** [comment]
Moving to review so we can proceed with separate ticket as POAM item
