### ISSUE TITLE
[ATO] Security Controls documentation (System and Communications Protection)

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#92]
Need to complete System and Communications Protection section of [Security Controls ](https://acf-headstart.box.com/s/dzrw2lcs1gzrtxli5ngteq5vmvtealr7) document.

[Previous ATO Controls](https://acf-headstart.box.com/s/dkzxy3ojktuy00pwf7pv6clsjgruphec)

AC:
[ ] System and Communications Protection section of Security Controls filled out
[ ] Reviewed internally and submitted to ISSO

**Comment by jduss4** [comment]
SC-05 I think we can build this up a bit with other DDOS combatting resources
