### ISSUE TITLE
ATO Network Topology

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#96]
Write a script to scrape all the SGs from AWS and put them in a chart with their inbound and outbound rules, and associated VPC.

Put this in a table similar to the one from section 2.10 in this doc: 
https://app.box.com/file/709848331555?s=lzit5omghlnt62ib2a23z48wd5v75hax

AC:

* [ ] Table exists for AWS SGs with inbound and outbound rules and associated VPC.
* [ ] Reviewed by Alana

**Comment by ssatagopan** [comment]
Included in network diagram as part of System Architecture document
