### ISSUE TITLE
Mysql backup to s3 failure warning

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#99]
Emails to root@mail.eclkc.info indicate that a cron job running db backups is going well until it fails to upload them to s3

"An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records."

**Comment by eeeady** [comment]
Think I fixed this. 

Checked the cron job that was erroring and compared to the ldap server with similar back up job.

The iam roles attached to both instances should have allowed for back up uploads.

Tested by uploading a test file via AWS CLI to check basic functionality:
```
touch hello-<server>
aws s3 cp hello-<server> s3://eclkc_backups/hello-<server>
```

Used the aws cli configuration list functionality to show the configuration aws cli was using...
```
aws configure list
```

LDAP server showed, aws using the iam role attached to the server while mail showed a local configuration file. I renamed the configuration file located in ~/.aws/ then attempted the test s3 command. It seemed to work.

Closing. Please reopen if occurs again.
